name: lint shellcheck

on:
  pull_request:
    paths:
      - '.github/workflows/lint-shellcheck.yml'
      - '*.sh'

jobs:
  lint-shellcheck:
    runs-on: ubuntu-24.04

    steps:
       - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

       - uses: reviewdog/action-shellcheck@v1.32.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           reporter: github-pr-check
